a = input('digite alguma coisa:')
print(a)
print('o tipo primitivo desse valor é {}' .format(type(a)))
print(a.isspace())
print(a.isnumeric())
print(a.isalpha())
print(a.isalnum())
print(a.istitle())
print(a.isupper())
print(a.islower())
print(a.isprintable())